global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'shopizer-services'
    static_configs:
      - targets: ['shopizer:8080', 'shopizer-db:3306', 'shopizer-admin:4200', 'shopizer-shop:80']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
